name: Release

on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version (e.g. 0.0.1)'
        required: true

env:
  JAVA_VERSION: 21

jobs:

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Show release version
        run: echo ${{ inputs.release_version }}
      - name: Check out code of the release
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ inputs.release_version }}
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'temurin'
          architecture: 'x64'
          cache: maven
      - name: Build Spring Boot Jar File
        run: mvn -e clean package
      - name: List files under target folder
        run: ls -l target
      - name: Build docker image
        run: ./docker-build.sh ${{ inputs.release_version }}
      - name: Show docker images
        run: docker images
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Push docker image to Docker Hub
        run: docker push apitestbase/sample-jms-services --all-tags
      - name: Upload docker-compose.yaml to release, to enable download from readme
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ inputs.release_version }}
          files: docker-compose.yaml

