name: Release on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  Call-Sub-Workflow:
    uses: ./.github/workflows/release.yml
    with:
      release_version: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}